const configs = {
  // vibrant-鲜艳度  muted-柔和度 saturation-饱和度
 DEFAULT_NON_MODE_PALETTE : 0,//if you don't need the ColorDic(including modeKey-colorModel key-value)
 VIBRANT_PALETTE : 1 << 0,
 LIGHT_VIBRANT_PALETTE : 1 << 1,
 DARK_VIBRANT_PALETTE : 1 << 2,
 LIGHT_MUTED_PALETTE : 1 << 3,
 MUTED_PALETTE : 1 << 4,
 DARK_MUTED_PALETTE : 1 << 5,
 ALL_MODE_PALETTE : 1 << 6,
 QUANTIZE_WORD_WIDTH : 5,
 kMaxColorNum : 16,

 COMPONENT_RED : 0,
 COMPONENT_GREEN : 1,
 COMPONENT_BLUE : 2,

  TARGET_DARK_LUMA : 0.26,
  MAX_DARK_LUMA : 0.45,

  MIN_LIGHT_LUMA : 0.55,
  TARGET_LIGHT_LUMA : 0.74,

  MIN_NORMAL_LUMA : 0.3,
  TARGET_NORMAL_LUMA : 0.5,
  MAX_NORMAL_LUMA : 0.7,

  TARGET_MUTED_SATURATION : 0.3,
  MAX_MUTED_SATURATION : 0.4,

  TARGET_VIBRANT_SATURATION : 1.0,
  MIN_VIBRANT_SATURATION : 0.35,

  WEIGHT_SATURATION : 0.24,
  WEIGHT_LUMA : 0.52,
  WEIGHT_POPULATION : 0.24,

  INDEX_MIN : 0,
  INDEX_TARGET : 1,
  INDEX_MAX : 2,

  INDEX_WEIGHT_SAT : 0,
  INDEX_WEIGHT_LUMA : 1,
  INDEX_WEIGHT_POP : 2
};

export default configs;
